name: Setup PHP & Composer
description: Setup PHP and Composer if not already installed

inputs:
  php:
    description: PHP version to use
    required: false
    default: '8.4'
  working-directory:
    description: Working directory to run Composer commands in
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup PHP
      id: setup_php
      if: ${{ !env.INSTALLED_PHP_VERSION }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php }}
        tools: composer:v2

    - name: Configure platform PHP version
      if: ${{ !env.INSTALLED_PHP_VERSION }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: composer config platform.php ${{ steps.setup_php.outputs.php-version }}

    - name: Output installed versions
      if: ${{ !env.INSTALLED_PHP_VERSION }}
      shell: bash
      run: |
        {
          echo "- PHP: $(php -r 'echo PHP_VERSION;')"
          echo "- Composer: $(composer --version --no-ansi)"
        } | tee -a "$GITHUB_STEP_SUMMARY"

    - name: Mark PHP setup done
      if: ${{ !env.INSTALLED_PHP_VERSION }}
      shell: bash
      run: echo "INSTALLED_PHP_VERSION=${{ steps.setup_php.outputs.php-version }}" >> "$GITHUB_ENV"
