name: Run Laravel Tests
description: Install Laravel dependencies and run Pest tests

inputs:
  php:
    description: PHP version to use
    required: false
    default: '8.4'
  laravel:
    description: Laravel version constraint (e.g. "11.*")
    required: false
    default: '12.*'

runs:
  using: composite
  steps:
    - name: Setup Composer
      uses: lepusinc/.github/.github/actions/php/setup-composer@main
      with:
        php: ${{ inputs.php }}

    - name: Install Laravel dependencies
      shell: bash
      run: composer require --dev "laravel/framework:${{ inputs.laravel }}" "orchestra/testbench" "pestphp/pest-plugin-laravel" --no-interaction --no-update

    - name: Run tests
      uses: lepusinc/.github/.github/actions/php/run-test@main
      with:
        php: ${{ inputs.php }}