name: Setup PHP Test Environment
description: Setup PHP, generate composer.lock, and install Composer packages

inputs:
  php:
    description: PHP version to use
    required: false
    default: '8.4'
  working-directory:
    description: Working directory to run Composer commands in
    required: false
    default: '.'

runs:
  using: composite
  steps:
    - name: Setup Composer
      uses: lepusinc/.github/.github/actions/php/setup-composer@v1
      with:
        php: ${{ inputs.php }}
        working-directory: ${{ inputs.working-directory }}

    - name: Generate composer.lock
      id: generate-lock
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        composer update --no-install --prefer-dist --no-interaction --no-progress
        working_dir="${{ inputs.working-directory }}"
        echo "path=${working_dir%/}/composer.lock" | tee -a "$GITHUB_STEP_SUMMARY" "$GITHUB_OUTPUT"

    - name: Get Composer cache directory
      id: composer-cache-dir
      shell: bash
      run: echo "path=$(composer config cache-dir)" | tee -a "$GITHUB_STEP_SUMMARY" "$GITHUB_OUTPUT"

    - name: Cache Composer files
      uses: actions/cache@v5
      with:
        path: ${{ steps.composer-cache-dir.outputs.path }}
        key: ${{ runner.os }}-composer-${{ hashFiles(steps.generate-lock.outputs.path) }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: composer install --prefer-dist --no-interaction --no-progress

    - name: Output installed versions
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: composer show --no-ansi | tee -a "$GITHUB_STEP_SUMMARY"
